# Generated by Django 4.2.7 on 2025-08-25 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="weigth",
            new_name="weight",
        ),
    ]
